### ISSUE TITLE
SQL ERROR 

### ISSUE THREAD

**Issue by itzzzyashu** [rsktg/TheRealPhoenixBot#14]
I've tried changing Integer in user_id Columns in all sql files but still it's showing same error `[SQL: INSERT INTO users (user_id, username) VALUES (%(user_id)s, %(username)s)]`

I'm confused, have to replace `BigInteger` or `BIGINT`?

**Comment by fushinori** [comment]
There's no reason to change the files. You only have to alter your database's schema to match the changes we've already made. Check the commit history to find the queries you need to execute. Execute them with `psql` or whatever.

**Comment by itzzzzyashu** [comment]
> psql

`psql://database-link` ?

**Comment by itzzzyashu** [comment]
> There's no reason to change the files. You only have to alter your database's schema to match the changes we've already made. Check the commit history to find the queries you need to execute. Execute them with `psql` or whatever.

I'm getting this error : 
`sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range`
`[SQL: INSERT INTO users (user_id, username) VALUES (%(user_id)s, %(username)s)]`
`[parameters: {'user_id': 5051036337, 'username': 'idk108'}]`
`(Background on this error at: https://sqlalche.me/e/14/9h9h)`

**Comment by fushinori** [comment]
Again, that's because you haven't changed your schema. Google how to use `psql` and use it to alter your database's schema. All you need to do is look at the commit history and copy-paste the queries we've already painstakingly written there for you.

**Comment by Dank-del** [comment]
> > There's no reason to change the files. You only have to alter your database's schema to match the changes we've already made. Check the commit history to find the queries you need to execute. Execute them with `psql` or whatever.
> 
> I'm getting this error : `sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range` `[SQL: INSERT INTO users (user_id, username) VALUES (%(user_id)s, %(username)s)]` `[parameters: {'user_id': 5051036337, 'username': 'idk108'}]` `(Background on this error at: https://sqlalche.me/e/14/9h9h)`

![image](https://user-images.githubusercontent.com/63096193/147845550-207c4d4d-605c-422c-9ab5-2fa33996b3d8.png)
copy paste the text here from those sql commits

**Comment by itzzzyashu** [comment]
> Google how to use `psql` and use it to alter your database's schema

ok got it, thanks !
